// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhXQDYOFIgNb9cqVYaTXexvptZ2pDjM4k',
    appId: '1:354666025392:web:c74f12b4ffb8c3d1f90675',
    messagingSenderId: '354666025392',
    projectId: 'facebook-clone-58449',
    authDomain: 'facebook-clone-58449.firebaseapp.com',
    storageBucket: 'facebook-clone-58449.firebasestorage.app',
    measurementId: 'G-NLF646KRB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgep0iMFzO5fgQIOBF36dHA7T2MoSUEtI',
    appId: '1:354666025392:android:a8c98d2153e3181df90675',
    messagingSenderId: '354666025392',
    projectId: 'facebook-clone-58449',
    storageBucket: 'facebook-clone-58449.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd5h61mUJDDCkRFZDTt7ocSErlL63znLo',
    appId: '1:354666025392:ios:819d6a4af383be67f90675',
    messagingSenderId: '354666025392',
    projectId: 'facebook-clone-58449',
    storageBucket: 'facebook-clone-58449.firebasestorage.app',
    iosClientId: '354666025392-p9k9f09h6i7db3lg0jsbutgl4o8tvte4.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd5h61mUJDDCkRFZDTt7ocSErlL63znLo',
    appId: '1:354666025392:ios:819d6a4af383be67f90675',
    messagingSenderId: '354666025392',
    projectId: 'facebook-clone-58449',
    storageBucket: 'facebook-clone-58449.firebasestorage.app',
    iosClientId: '354666025392-p9k9f09h6i7db3lg0jsbutgl4o8tvte4.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhXQDYOFIgNb9cqVYaTXexvptZ2pDjM4k',
    appId: '1:354666025392:web:acb7ec9f91e46463f90675',
    messagingSenderId: '354666025392',
    projectId: 'facebook-clone-58449',
    authDomain: 'facebook-clone-58449.firebaseapp.com',
    storageBucket: 'facebook-clone-58449.firebasestorage.app',
    measurementId: 'G-P588WVQD66',
  );
}
